version: '3.8'
services:

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    volumes:
      - app-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pa55word

  demo-microservice:
    build: .
    container_name: demo-microservice
    environment:
      - SERVER_PORT=8080
      - DATABASE_NAME=demo
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=Pa55word
    ports:
      - 8080:8080
    links:
      - postgres-db

volumes:
  app-data:
    driver: local