version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    ports:
      - ${DATASOURCE_PORT}:5432
    networks:
      - common-net
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  demo-microservice:
    build: .
    container_name: demo-microservice
    volumes:
      - .:/src
    ports:
      - ${SERVER_PORT}:8080
    networks:
      - common-net
    links:
      - postgres-db
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATASOURCE_HOST=${DATASOURCE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_PORT=${DATASOURCE_PORT}
volumes:
  db-data:
networks:
  common-net: